version: "3.8"

services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: nginx

        ports:
          - "8081:8080"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
          - ./client/build/:/usr/src/client
          - ./api/static/admin:/usr/src/client/static/admin

        depends_on:
          - api

    api:
        container_name: api
        build: ./api
        image: api

        # ports:
        #   - "8091:8090"
        volumes:
          - ./api/:/usr/src/api

        env_file:
          - ./.env
        depends_on:
          - db

    db:
        container_name: db
        build: ./db
        image: db

        volumes:
          - postgres_data:/var/lib/postgresql/data/
        
        env_file:
          - ./.env

volumes:
  postgres_data:

