FROM postgres:14.0-alpine
LABEL project="clare"

# RUN addgroup -S api_group; \
# 	adduser -S api_user -G api_group;

USER postgres

# RUN addgroup -S -g $GID $GROUP; \
# 	adduser -S -u $UID $USER -G $GROUP;

# USER $USER


EXPOSE 5432

# CMD ["psql", "$POSTGRES_USER", "$POSTGRES_DB"]

# RUN localedef -i ru_RU -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8
# ENV LANG de_DE.utf8